/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Magic-byte detection reads only the head of the buffer. We bound the
 * copy at 4 KB so 10 MB inputs don't pay a full memcpy before the
 * worker thread even starts.
 */
export declare function fileTypeFromBuffer(buffer: Buffer): Promise<FileTypeResult | null>

export declare function fileTypeFromBufferSync(buffer: Buffer): FileTypeResult | null

export interface FileTypeResult {
  ext: string
  mime: string
}
