/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function fileTypeFromBuffer(buffer: Buffer): Promise<FileTypeResult | null>

export declare function fileTypeFromBufferSync(buffer: Buffer): FileTypeResult | null

export interface FileTypeResult {
  ext: string
  mime: string
}
