/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Magic-byte detection reads only the head of the buffer. We bound the
 * copy at 4 KB so 10 MB inputs don't pay a full memcpy before the
 * worker thread even starts.
 */
export declare function fileTypeFromBuffer(buffer: Buffer): Promise<FileTypeResult | null>

export declare function fileTypeFromBufferSync(buffer: Buffer): FileTypeResult | null

export interface FileTypeResult {
  ext: string
  mime: string
}
