/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Bm25Index {
  constructor(options?: IndexOptions | undefined | null)
  /**
   * Ingest a batch of documents — single FFI crossing for the
   * whole corpus. Preferred over repeated `addDoc`.
   */
  addAll(docs: Array<BmDocument>): void
  /** Add a single document. Prefer `addAll` for bulk ingest. */
  addDoc(id: string, text: string): void
  search(query: string, options?: SearchOptions | undefined | null): Array<SearchHit>
  size(): number
}

export interface BmDocument {
  id: string
  text: string
}

export interface IndexOptions {
  /** BM25 `k1`. Default 1.5. */
  k1?: number
  /** BM25 `b`. Default 0.75. */
  b?: number
  /** Strip English stopwords during tokenization. Default false. */
  removeStopwords?: boolean
}

export interface SearchHit {
  id: string
  score: number
}

export interface SearchOptions {
  /** Maximum hits to return. Default 10. */
  limit?: number
}
