/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Bm25Index {
  constructor(options?: IndexOptions | undefined | null)
  /**
   * Ingest a batch of documents — single FFI crossing for the
   * whole corpus. Preferred over repeated `addDoc`.
   */
  addAll(docs: Array<BmDocument>): void
  /** Add a single document. Prefer `addAll` for bulk ingest. */
  addDoc(id: string, text: string): void
  search(query: string, options?: SearchOptions | undefined | null): Array<SearchHit>
  size(): number
}

export interface BmDocument {
  id: string
  text: string
}

export interface IndexOptions {
  /** BM25 `k1`. Default 1.5. */
  k1?: number
  /** BM25 `b`. Default 0.75. */
  b?: number
  /** Strip English stopwords during tokenization. Default false. */
  removeStopwords?: boolean
}

export interface SearchHit {
  id: string
  score: number
}

export interface SearchOptions {
  /** Maximum hits to return. Default 10. */
  limit?: number
}
