/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function getDomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getHostname(input: string): string | null

export declare function getPublicSuffix(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getSubdomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function parse(input: string, options?: ParseOptions | undefined | null): ParseResult

export declare function parseMany(inputs: Array<string>, options?: ParseOptions | undefined | null): ParseManyResult

export interface ParseManyResult {
  domains: Array<string | undefined | null>
  publicSuffixes: Array<string | undefined | null>
  flags: Buffer
}

export interface ParseOptions {
  allowPrivateDomains?: boolean
  detectIp?: boolean
  extractHostname?: boolean
}

export interface ParseResult {
  hostname?: string
  domain?: string
  subdomain?: string
  publicSuffix?: string
  isIcann: boolean
  isPrivate: boolean
  isIp: boolean
}
