/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getDomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getHostname(input: string): string | null

export declare function getPublicSuffix(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getSubdomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function parse(input: string, options?: ParseOptions | undefined | null): ParseResult

export declare function parseMany(inputs: Array<string>, options?: ParseOptions | undefined | null): ParseManyResult

export interface ParseManyResult {
  domains: Array<string | undefined | null>
  publicSuffixes: Array<string | undefined | null>
  flags: Buffer
}

export interface ParseOptions {
  allowPrivateDomains?: boolean
  detectIp?: boolean
  extractHostname?: boolean
}

export interface ParseResult {
  hostname?: string
  domain?: string
  subdomain?: string
  publicSuffix?: string
  isIcann: boolean
  isPrivate: boolean
  isIp: boolean
}
