/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getDomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getHostname(input: string): string | null

export declare function getPublicSuffix(input: string, options?: ParseOptions | undefined | null): string | null

export declare function getSubdomain(input: string, options?: ParseOptions | undefined | null): string | null

export declare function parse(input: string, options?: ParseOptions | undefined | null): ParseResult

export declare function parseMany(inputs: Array<string>, options?: ParseOptions | undefined | null): ParseManyResult

export interface ParseManyResult {
  domains: Array<string | undefined | null>
  publicSuffixes: Array<string | undefined | null>
  flags: Buffer
}

/**
 * v0.1 ParseOptions surface. Several upstream `tldts` options have no
 * effect in this implementation:
 *
 * - `allow_private_domains`: the `psl` crate's bundled IANA list does
 *   not distinguish ICANN vs PRIVATE sections. Both are honoured. This
 *   means private-suffix domains (e.g. `*.appspot.com`) are always
 *   parsed as their full subdomain.something.appspot.com regardless of
 *   this flag. Fixing this requires switching to the `publicsuffix`
 *   crate which exposes section metadata; tracked for v0.2.
 * - `detect_ip`: IP-detection is always on. Setting this to `false`
 *   has no effect.
 *
 * `extract_hostname` is the one option that's meaningful: when `false`,
 * the input is treated as a bare hostname (no scheme/path stripping).
 */
export interface ParseOptions {
  allowPrivateDomains?: boolean
  detectIp?: boolean
  extractHostname?: boolean
}

export interface ParseResult {
  hostname?: string
  domain?: string
  subdomain?: string
  publicSuffix?: string
  isIcann: boolean
  isPrivate: boolean
  isIp: boolean
}
