/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Unified-diff-format patch string. */
export declare function createPatch(fileName: string, oldStr: string, newStr: string, oldHeader?: string | undefined | null, newHeader?: string | undefined | null): string

/** Char-level diff. Output: jsdiff-compatible hunk array. */
export declare function diffChars(oldStr: string, newStr: string): Array<Hunk>

/** Offset-packed char diff. Same layout as `diffLinesToOffsets`. */
export declare function diffCharsToOffsets(oldStr: string, newStr: string): Buffer

/** Line-level diff — the most common shape for code-review tooling. */
export declare function diffLines(oldStr: string, newStr: string): Array<Hunk>

/**
 * Offset-packed line diff. Returns a Uint32Array laid out as
 * `[type, oldStart, oldEnd, newStart, newEnd, …]` where `type` is
 * `0 = equal`, `1 = added`, `2 = removed`. Caller slices the source
 * strings lazily — no per-hunk JS-string marshalling.
 *
 * This is the Green hot-path for large or char-level diffs where the
 * hunk-array shape drowns in Vec<String> allocation.
 */
export declare function diffLinesToOffsets(oldStr: string, newStr: string): Buffer

/**
 * Line diff that trims trailing whitespace — mirrors `diffTrimmedLines`
 * from jsdiff by preprocessing inputs.
 */
export declare function diffTrimmedLines(oldStr: string, newStr: string): Array<Hunk>

/** Word-level diff. */
export declare function diffWords(oldStr: string, newStr: string): Array<Hunk>

export interface Hunk {
  value: string
  added?: boolean
  removed?: boolean
}
