/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function createPatch(fileName: string, oldStr: string, newStr: string, oldHeader?: string | undefined | null, newHeader?: string | undefined | null): string

export declare function diffChars(oldStr: string, newStr: string): Array<Hunk>

export declare function diffCharsToOffsets(oldStr: string, newStr: string): Buffer

export declare function diffLines(oldStr: string, newStr: string): Array<Hunk>

export declare function diffLinesToOffsets(oldStr: string, newStr: string): Buffer

export declare function diffTrimmedLines(oldStr: string, newStr: string): Array<Hunk>

export declare function diffWords(oldStr: string, newStr: string): Array<Hunk>

export interface Hunk {
  value: string
  added?: boolean
  removed?: boolean
}
