/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Count rows without building JS arrays — pure Rust speed, zero FFI-per-row overhead. */
export declare function countRows(input: Buffer, options?: CsvOptions | undefined | null): number

export interface CsvOptions {
  delimiter?: number
  hasHeaders?: boolean
  quoteChar?: number
  escapeChar?: number
  comment?: number
  flexible?: boolean
  trimFields?: boolean
}

export declare function parse(input: Buffer, options?: CsvOptions | undefined | null): Array<Array<string>>

/**
 * Parse CSV and return rows as a flat JSON string.
 * Avoids per-row FFI overhead — one large string transfer instead of N×M small ones.
 * Use JSON.parse() on the JS side.
 */
export declare function parseToJson(input: Buffer, options?: CsvOptions | undefined | null): string

export declare function parseWithHeaders(input: Buffer, options?: CsvOptions | undefined | null): Array<Record<string, string>>

export declare function stringify(rows: Array<Array<string>>, options?: CsvOptions | undefined | null): string

export declare function stringifyObjects(rows: Array<Record<string, string>>, columns?: Array<string> | undefined | null, options?: CsvOptions | undefined | null): string
