/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CsvOptions {
  delimiter?: number
  hasHeaders?: boolean
  quoteChar?: number
  escapeChar?: number
  comment?: number
  flexible?: boolean
  trimFields?: boolean
}

export declare function parse(input: Buffer, options?: CsvOptions | undefined | null): Array<Array<string>>

export declare function parseWithHeaders(input: Buffer, options?: CsvOptions | undefined | null): Array<Record<string, string>>

export declare function stringify(rows: Array<Array<string>>, options?: CsvOptions | undefined | null): string

export declare function stringifyObjects(rows: Array<Record<string, string>>, columns?: Array<string> | undefined | null, options?: CsvOptions | undefined | null): string
