/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function countRows(input: Buffer, options?: CsvOptions | undefined | null): number

export interface CsvOptions {
  delimiter?: number
  hasHeaders?: boolean
  quoteChar?: number
  escapeChar?: number
  comment?: number
  flexible?: boolean
  trimFields?: boolean
}

export declare function parse(input: Buffer, options?: CsvOptions | undefined | null): Array<Array<string>>

export declare function parseToJson(input: Buffer, options?: CsvOptions | undefined | null): string

export declare function parseWithHeaders(input: Buffer, options?: CsvOptions | undefined | null): Array<Record<string, string>>

export declare function stringify(rows: Array<Array<string>>, options?: CsvOptions | undefined | null): string

export declare function stringifyObjects(rows: Array<Record<string, string>>, columns?: Array<string> | undefined | null, options?: CsvOptions | undefined | null): string
