/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function decodeToken(token: string): VerifyResult

export declare function sign(payload: any, secret: Buffer, options?: SignOptions | undefined | null): Promise<string>

export interface SignOptions {
  /** "HS256" (default), "HS384", "HS512", "RS256", etc. */
  algorithm?: string
  /**
   * Until-expiry. Seconds as a number (`3600`), or an `ms`-package-compatible
   * string (`"1h"`, `"2 days"`, `"1500"` for 1500 ms). Maps to `exp` claim.
   */
  expiresIn?: any
  /** Becomes-valid. Same shape as `expiresIn`. Maps to `nbf` claim. */
  notBefore?: any
  audience?: string
  issuer?: string
  subject?: string
  jwtid?: string
  /** Additional raw header fields as JSON. */
  header?: any
}

export declare function signSync(payload: any, secret: Buffer, options?: SignOptions | undefined | null): string

export declare function verify(token: string, secret: Buffer, options?: VerifyOptions | undefined | null): Promise<VerifyResult>

export interface VerifyOptions {
  /** Allowed algorithms. Defaults to [HS256]. */
  algorithms?: Array<string>
  audience?: string
  issuer?: string
  subject?: string
  /** Clock skew tolerance in seconds (default 0). */
  clockTolerance?: number
  /** If false, skip `exp` check. */
  ignoreExpiration?: boolean
  /** If false, skip `nbf` check. */
  ignoreNotBefore?: boolean
}

export interface VerifyResult {
  payload: any
  header: any
}

export declare function verifySync(token: string, secret: Buffer, options?: VerifyOptions | undefined | null): VerifyResult
