/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Document {
  title?: string
  pages: Array<Page>
}

/** Generate a PDF from a document spec. Single FFI crossing. */
export declare function generate(doc: Document): Buffer

/**
 * Batch-generate N documents. One FFI crossing for the whole
 * label-printing job.
 */
export declare function generateMany(docs: Array<Document>): Array<Buffer>

export interface LineElement {
  kind: string
  x1: number
  y1: number
  x2: number
  y2: number
  thickness?: number
}

export interface Page {
  width: number
  height: number
  elements: Array<PdfElement>
}

export interface PdfElement {
  kind: string
  text?: TextElement
  line?: LineElement
  rect?: RectElement
}

export interface RectElement {
  kind: string
  x: number
  y: number
  width: number
  height: number
  filled?: boolean
}

export interface TextElement {
  kind: string
  x: number
  y: number
  text: string
  fontSize?: number
}
