/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parseXml(input: string, strict?: boolean | undefined | null): Array<XmlEvent>

export interface XmlAttr {
  name: string
  value: string
}

export interface XmlEvent {
  /**
   * One of: "opentag", "closetag", "text", "cdata", "comment",
   * "processinginstruction", "doctype".
   */
  kind: string
  name?: string
  text?: string
  attrs?: Array<XmlAttr>
  selfClosing?: boolean
}
