/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  constructor(options?: CommonMarkOptions | undefined | null)
  render(markdown: string): string
  renderBytes(markdown: Buffer): string
}

export interface CommonMarkOptions {
  gfm?: boolean
  footnotes?: boolean
  smartPunctuation?: boolean
  unsafeHtml?: boolean
  headingIds?: boolean
}

export declare function render(markdown: string, options?: CommonMarkOptions | undefined | null): string

/**
 * Render from a UTF-8 byte buffer. Skips the V8 UTF-16 → UTF-8 copy on
 * the FFI boundary — measurably faster for inputs ≥ ~10 KB (see
 * `docs/BASELINE.md`: ~0.35 ns/byte on string input vs. flat 170 ns
 * on Buffer input).
 */
export declare function renderBytes(markdown: Buffer, options?: CommonMarkOptions | undefined | null): string

export declare function renderMany(docs: Array<string>, options?: CommonMarkOptions | undefined | null): Array<string>
