/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Renderer {
  constructor(options?: CommonMarkOptions | undefined | null)
  render(markdown: string): string
}

export interface CommonMarkOptions {
  gfm?: boolean
  footnotes?: boolean
  smartPunctuation?: boolean
  unsafeHtml?: boolean
  headingIds?: boolean
}

export declare function render(markdown: string, options?: CommonMarkOptions | undefined | null): string

export declare function renderMany(docs: Array<string>, options?: CommonMarkOptions | undefined | null): Array<string>
