/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Generate a fresh Ed25519 key-pair as JWKs (RFC 8037 OKP form).
 *
 * Synchronous: Ed25519 key generation is microsecond-scale.
 */
export declare function generateEd25519KeyPair(): JwkKeyPair

/**
 * Generate a fresh RSA key-pair as JWKs.
 *
 * `bits` must be ≥ 2048. Generation is CPU-bound and runs on the libuv
 * thread-pool — typically 100ms–3s depending on key size.
 */
export declare function generateRsaKeyPair(bits?: number | undefined | null): Promise<JwkKeyPair>

/** A JWK key-pair — both public and private representations of the same key. */
export interface JwkKeyPair {
  publicJwk: any
  privateJwk: any
}

/**
 * Compute the SHA-256 JWK thumbprint per RFC 7638.
 *
 * The thumbprint is a stable, kid-independent identifier for the key. The
 * caller passes either a public or private JWK; only the canonical required
 * fields are hashed (no `kid`, no `alg`, no private-key components).
 */
export declare function jwkThumbprint(jwk: any): string
