/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface JwkKeyPair {
  publicJwk: unknown
  privateJwk: unknown
}

export declare function generateRsaKeyPair(bits?: number | undefined | null): Promise<JwkKeyPair>

export declare function generateEd25519KeyPair(): JwkKeyPair

export declare function jwkThumbprint(jwk: unknown): string
