/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * Generate a fresh Ed25519 key-pair as JWKs (RFC 8037 OKP form).
 *
 * Synchronous: Ed25519 key generation is microsecond-scale.
 */
export declare function generateEd25519KeyPair(): JwkKeyPair

/** A JWK key-pair — both public and private representations of the same key. */
export interface JwkKeyPair {
  publicJwk: any
  privateJwk: any
}

/**
 * Compute the SHA-256 JWK thumbprint per RFC 7638.
 *
 * The thumbprint is a stable, kid-independent identifier for the key. The
 * caller passes either a public or private JWK; only the canonical required
 * fields are hashed (no `kid`, no `alg`, no private-key components).
 */
export declare function jwkThumbprint(jwk: any): string
