/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decode(input: Buffer): DecodedJpeg

export interface DecodedJpeg {
  width: number
  height: number
  data: Buffer
}

export declare function decodeRgba(input: Buffer): DecodedJpeg

export declare function encode(image: DecodedJpeg, quality?: number | undefined | null): EncodedJpeg

export interface EncodedJpeg {
  data: Buffer
  width: number
  height: number
}

export interface EncodeOptions {
  quality?: number
}

export declare function encodeRgba(pixels: Buffer, width: number, height: number, opts?: EncodeOptions | undefined | null): Buffer
