/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function decode(input: Buffer): DecodedJpeg

export interface DecodedJpeg {
  width: number
  height: number
  data: Buffer
}

export declare function decodeRgba(input: Buffer): DecodedJpeg

export declare function encode(image: DecodedJpeg, quality?: number | undefined | null): EncodedJpeg

export interface EncodedJpeg {
  data: Buffer
  width: number
  height: number
}

export interface EncodeOptions {
  quality?: number
}

export declare function encodeRgba(pixels: Buffer, width: number, height: number, opts?: EncodeOptions | undefined | null): Buffer
