/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function turndown(html: string, options?: TurndownOptions | undefined | null): string

export declare function turndownBatch(htmls: Array<string>, options?: TurndownOptions | undefined | null): Array<string>

export interface TurndownOptions {
  /** `atx` (default: `# Heading`) or `setext` (underline style). */
  headingStyle?: string
  /** Thematic-break marker. Default `* * *`. */
  hr?: string
  /** `*`, `-`, or `+`. Default `*`. */
  bulletListMarker?: string
  /** `indented` or `fenced`. Default `indented`. */
  codeBlockStyle?: string
  /** `` ``` `` or `~~~`. Default `` ``` ``. */
  fence?: string
  /** `_` or `*`. Default `_`. */
  emDelimiter?: string
  /** `__` or `**`. Default `**`. */
  strongDelimiter?: string
  /** `inlined` or `referenced`. Default `inlined`. */
  linkStyle?: string
  /**
   * Enable GitHub-Flavored Markdown: tables, strikethrough,
   * task-lists. Default `false`.
   */
  gfm?: boolean
  /** Tags to keep as raw HTML in the output. */
  keep?: Array<string>
  /** Tags to remove entirely (including content). */
  remove?: Array<string>
}
