/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function turndown(html: string, options?: TurndownOptions | undefined | null): string

export declare function turndownBatch(htmls: Array<string>, options?: TurndownOptions | undefined | null): Array<string>

export interface TurndownOptions {
  headingStyle?: string
  hr?: string
  bulletListMarker?: string
  codeBlockStyle?: string
  fence?: string
  emDelimiter?: string
  strongDelimiter?: string
  linkStyle?: string
  gfm?: boolean
  keep?: Array<string>
  remove?: Array<string>
}
