/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function turndown(html: string, options?: TurndownOptions | undefined | null): string

export declare function turndownBatch(htmls: Array<string>, options?: TurndownOptions | undefined | null): Array<string>

export interface TurndownOptions {
  headingStyle?: string
  hr?: string
  bulletListMarker?: string
  codeBlockStyle?: string
  fence?: string
  emDelimiter?: string
  strongDelimiter?: string
  linkStyle?: string
  gfm?: boolean
  keep?: Array<string>
  remove?: Array<string>
}
