/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function nanoid(size?: number | undefined | null): string

/**
 * Batch API: generate `count` ids in a single FFI call. Each call to
 * `nanoid()` pays ~1.5µs N-API string-allocation overhead; for large
 * batches (>>100) this amortises the cost across the whole array.
 */
export declare function nanoidBatch(count: number, size?: number | undefined | null): Array<string>

export declare function nanoidCustom(alphabet: string, size?: number | undefined | null): string

export declare function nanoidCustomBatch(alphabet: string, count: number, size?: number | undefined | null): Array<string>
