/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function nanoid(size?: number | undefined | null): string

export declare function nanoidCustom(alphabet: string, size?: number | undefined | null): string
