/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface CellValue {
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

export declare function readSheet(buf: Buffer, sheetName: string): Sheet

export declare function readSheetAsObjects(buf: Buffer, sheetName: string): Array<Record<string, CellValue>>

export declare function readWorkbook(buf: Buffer): Workbook2

export interface Sheet {
  name: string
  rows: Array<Array<CellValue>>
}

export interface Workbook2 {
  sheets: Array<Sheet>
}

export interface WriteCell {
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

export interface WriteSheet {
  name: string
  rows: Array<Array<WriteCell>>
}

export declare function writeSheetFromObjects(sheetName: string, rows: Array<Record<string, WriteCell>>): Buffer

export declare function writeWorkbook(sheets: Array<WriteSheet>): Buffer
