/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CellValue {
  /** `"string"`, `"number"`, `"bool"`, `"date"`, or `"empty"`. */
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

/** Read only a named sheet. */
export declare function readSheet(buf: Buffer, sheetName: string): Sheet

/**
 * Convert a sheet to an array-of-objects using the first row as
 * headers (SheetJS's `sheet_to_json` equivalent).
 */
export declare function readSheetAsObjects(buf: Buffer, sheetName: string): Array<Record<string, CellValue>>

/** Parse a XLSX workbook from a Buffer. Returns every sheet. */
export declare function readWorkbook(buf: Buffer): Workbook2

export interface Sheet {
  name: string
  rows: Array<Array<CellValue>>
}

export interface Workbook2 {
  sheets: Array<Sheet>
}

export interface WriteCell {
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

export interface WriteSheet {
  name: string
  rows: Array<Array<WriteCell>>
}

/**
 * Write from an array-of-objects. The first object's keys define
 * the header row; missing values are emitted as blank cells.
 */
export declare function writeSheetFromObjects(sheetName: string, rows: Array<Record<string, WriteCell>>): Buffer

/** Serialize a workbook (sheets + rows) to an XLSX Buffer. */
export declare function writeWorkbook(sheets: Array<WriteSheet>): Buffer
