/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface CellValue {
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

export declare function readSheet(buf: Buffer, sheetName: string): Sheet

export declare function readSheetAsObjects(buf: Buffer, sheetName: string): Array<Record<string, CellValue>>

export declare function readWorkbook(buf: Buffer): Workbook2

export interface Sheet {
  name: string
  rows: Array<Array<CellValue>>
}

export interface Workbook2 {
  sheets: Array<Sheet>
}

export interface WriteCell {
  kind: string
  text?: string
  number?: number
  boolValue?: boolean
}

export interface WriteSheet {
  name: string
  rows: Array<Array<WriteCell>>
}

export declare function writeSheetFromObjects(sheetName: string, rows: Array<Record<string, WriteCell>>): Buffer

export declare function writeWorkbook(sheets: Array<WriteSheet>): Buffer
