/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ZipReader {
  /** Accepts either a Buffer or a filesystem path. */
  static fromBuffer(buffer: Buffer): ZipReader
  static fromPath(path: string): ZipReader
  entries(): Array<ZipEntryInfo>
  read(name: string): Buffer
}

export declare class ZipWriter {
  constructor()
  add(name: string, data: Buffer, options?: AddOptions | undefined | null): void
  finalize(): Buffer
}

export interface AddOptions {
  /** Compression method: "deflate" (default) or "stored". */
  compression?: string
  /** Deflate level 0-9 (default 6). */
  level?: number
}

export interface ZipEntryInfo {
  name: string
  size: number
  compressedSize: number
  isDir: boolean
  compression: string
}
