/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ZipReader {
  static fromBuffer(buffer: Buffer): ZipReader
  static fromPath(path: string): ZipReader
  entries(): Array<ZipEntryInfo>
  read(name: string): Buffer
  extractAll(): Array<ZipEntryData>
}

export declare class ZipWriter {
  constructor()
  add(name: string, data: Buffer, options?: AddOptions | undefined | null): void
  finalize(): Buffer
}

export interface AddOptions {
  compression?: string
  level?: number
}

export interface ZipEntryData {
  name: string
  data: Buffer
}

export interface ZipEntryInfo {
  name: string
  size: bigint
  compressedSize: bigint
  isDir: boolean
  compression: string
}
