/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ZipReader {
  /** Accepts either a Buffer or a filesystem path. */
  static fromBuffer(buffer: Buffer): ZipReader
  static fromPath(path: string): ZipReader
  entries(): Array<ZipEntryInfo>
  read(name: string): Buffer
  /**
   * One-shot: parse the archive once and return every (non-directory)
   * entry's uncompressed bytes along with its name. Replaces the
   * `for (e of entries()) read(e.name)` pattern, which re-parsed the
   * central directory on every iteration — O(N²) on number of
   * entries. This is O(N) and the one call users want for
   * "unzip to memory".
   */
  extractAll(): Array<ZipEntryData>
}

export declare class ZipWriter {
  constructor()
  add(name: string, data: Buffer, options?: AddOptions | undefined | null): void
  finalize(): Buffer
}

export interface AddOptions {
  /** Compression method: "deflate" (default) or "stored". */
  compression?: string
  /** Deflate level 0-9 (default 6). */
  level?: number
}

export interface ZipEntryData {
  name: string
  data: Buffer
}

export interface ZipEntryInfo {
  name: string
  /**
   * Uncompressed size in bytes. Exposed as `bigint` because legitimate
   * ZIP entries can exceed 4 GiB (zip64).
   *
   * Casting to `number` (`Number(entry.size)`) is only safe when the
   * caller knows the value fits in `Number.MAX_SAFE_INTEGER` (2^53 − 1,
   * ≈ 9 PiB). Above that the conversion silently rounds; prefer keeping
   * the value as `bigint` when handling untrusted archives.
   */
  size: bigint
  /** Compressed size in bytes. Same `bigint` semantics as `size`. */
  compressedSize: bigint
  isDir: boolean
  compression: string
}
