/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Deep structural equality for JSON-safe values. Accepts anything that
 * serialises through napi's serde bridge. Rejects the call (returns false)
 * rather than throwing for cyclic inputs — callers should detect cycles
 * JS-side via the wrapper.
 */
export declare function deepEqualJson(a: any, b: any): boolean
