/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function optimize(svg: string, config?: SvgoConfig | undefined | null): SvgoResult

export declare function optimizeMany(svgs: Array<string>, config?: SvgoConfig | undefined | null): Array<SvgoResult>

export interface SvgoConfig {
  removeComments?: boolean
  removeMetadata?: boolean
  removeTitle?: boolean
  removeDesc?: boolean
  removeDoctype?: boolean
  removeXmlProcInst?: boolean
  removeEditorsNsData?: boolean
  removeEmptyAttrs?: boolean
  removeEmptyText?: boolean
  removeEmptyContainers?: boolean
  removeHiddenElems?: boolean
  removeUselessDefs?: boolean
  cleanupNumericValues?: boolean
  cleanupAttrs?: boolean
  collapseGroups?: boolean
  convertColors?: boolean
  collapseWhitespace?: boolean
  /** Decimal places kept by `cleanupNumericValues`. Default: 3. */
  floatPrecision?: number
  multipass?: boolean
}

export interface SvgoResult {
  data: string
  inputBytes: number
  outputBytes: number
  savedPercent: number
}
