/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Jimp {
  static fromBuffer(input: Buffer): Jimp
  static create(width: number, height: number, color?: number | undefined | null): Jimp
  get width(): number
  get height(): number
  resize(w: number, h: number): void
  crop(x: number, y: number, w: number, h: number): void
  flip(horizontal: boolean, vertical: boolean): void
  rotate(deg: number): void
  greyscale(): void
  invert(): void
  brightness(value: number): void
  contrast(value: number): void
  composite(src: Jimp, x: number, y: number): void
  bitmap(): DecodedBitmap
  getBufferSync(mime: string): Buffer
}

export interface DecodedBitmap {
  width: number
  height: number
  data: Buffer
}
