/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Jimp {
  static fromBuffer(input: Buffer): Jimp
  static create(width: number, height: number, color?: number | undefined | null): Jimp
  get width(): number
  get height(): number
  resize(w: number, h: number): void
  crop(x: number, y: number, w: number, h: number): void
  flip(horizontal: boolean, vertical: boolean): void
  rotate(deg: number): void
  greyscale(): void
  invert(): void
  brightness(value: number): void
  contrast(value: number): void
  composite(src: Jimp, x: number, y: number): void
  bitmap(): DecodedBitmap
  getBufferSync(mime: string): Buffer
}

export interface DecodedBitmap {
  width: number
  height: number
  data: Buffer
}
