/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface FedgeSpec {
  source: string
  target: string
  /** Target link distance (pixels). Default 30. */
  distance?: number
  /** Link spring strength in [0,1]. Default 1/min(inbound, outbound). */
  strength?: number
}

export interface FnodeResult {
  id: string
  x: number
  y: number
  vx: number
  vy: number
}

export interface FnodeSpec {
  id: string
  x?: number
  y?: number
  /** Pin to x,y — skip forces. Default false. */
  fixed?: boolean
}

export declare function simulate(nodes: Array<FnodeSpec>, edges: Array<FedgeSpec>, options?: SimulationOptions | undefined | null): SimulationResult

export interface SimulationOptions {
  iterations?: number
  charge?: number
  collideRadius?: number
  centerX?: number
  centerY?: number
  centerStrength?: number
  alpha?: number
  alphaDecay?: number
  velocityDecay?: number
}

export interface SimulationResult {
  nodes: Array<FnodeResult>
}
