/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface FedgeSpec {
  source: string
  target: string
  /** Target link distance (pixels). Default 30. */
  distance?: number
  /** Link spring strength in [0,1]. Default 1/min(inbound, outbound). */
  strength?: number
}

export interface FnodeResult {
  id: string
  x: number
  y: number
  vx: number
  vy: number
}

export interface FnodeSpec {
  id: string
  x?: number
  y?: number
  /** Pin to x,y — skip forces. Default false. */
  fixed?: boolean
}

/**
 * Batch simulation — runs all iterations in Rust, returns final
 * positions. Preferred over tick-by-tick for SSR / precompute
 * workloads.
 */
export declare function simulate(nodes: Array<FnodeSpec>, edges: Array<FedgeSpec>, options?: SimulationOptions | undefined | null): SimulationResult

export interface SimulationOptions {
  /** Iterations to run. Default 300. */
  iterations?: number
  /** Many-body strength (negative = repulsion). Default -30. */
  charge?: number
  /** Radius for collision force. Default 0 (off). */
  collideRadius?: number
  /** Centre x. Default 0. */
  centerX?: number
  /** Centre y. Default 0. */
  centerY?: number
  /** Centering force strength. Default 0.1. */
  centerStrength?: number
  /** Initial alpha (cooling schedule). Default 1. */
  alpha?: number
  /** Alpha decay per iteration. Default computed from iterations. */
  alphaDecay?: number
  /** Velocity decay per iteration. Default 0.4. */
  velocityDecay?: number
}

export interface SimulationResult {
  nodes: Array<FnodeResult>
}
