/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function deflate(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function deflateRaw(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function gzip(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function inflate(data: Buffer): Buffer

export interface InflateOptions {
  /** Compression level 0–9 (default 6, analogous to pako). */
  level?: number
}

export declare function inflateRaw(data: Buffer): Buffer

export declare function ungzip(data: Buffer): Buffer
