/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function deflate(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function deflateRaw(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function gzip(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function inflate(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export interface InflateOptions {
  /** Compression level 0–9 (default 6, analogous to pako). */
  level?: number
  /**
   * Hard cap on decompressed output size in bytes. Defaults to 256 MiB.
   * Pass `0` to disable the cap (not recommended for untrusted input —
   * gzip bombs expand to terabytes).
   */
  maxOutputSize?: number
}

export declare function inflateRaw(data: Buffer, options?: InflateOptions | undefined | null): Buffer

export declare function ungzip(data: Buffer, options?: InflateOptions | undefined | null): Buffer
