/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MiniSearch {
  constructor(options?: MiniOptions | undefined | null)
  /** Single-FFI-crossing corpus ingest. */
  addAll(docs: Array<MiniDocument>): void
  add(doc: MiniDocument): void
  search(query: string, options?: MiniSearchOptions | undefined | null): Array<MiniHit>
  /**
   * Autocomplete: return the prefix-matching terms from the index,
   * ranked by how many docs contain them.
   */
  autoSuggest(prefix: string, limit?: number | undefined | null): Array<AutoSuggestion>
  size(): number
}

export interface AutoSuggestion {
  suggestion: string
  score: number
}

export interface MiniDocument {
  id: string
  text: string
}

export interface MiniHit {
  id: string
  score: number
}

export interface MiniOptions {
  k1?: number
  b?: number
  /** Strip English stopwords at index- and query-time. Default false. */
  removeStopwords?: boolean
  /**
   * Default operator for multi-term queries: `"OR"` (default) or
   * `"AND"`. AND requires every query token to appear in the doc.
   */
  defaultOperator?: string
}

export interface MiniSearchOptions {
  limit?: number
  /** Prefix-match: treat the last term as a prefix (autocomplete). */
  prefix?: boolean
  /** Override default operator for this query. */
  operator?: string
}
