/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Stemmer {
  constructor(language: string)
  /** Batch-stem a list of whole words. One FFI crossing each way. */
  stemMany(words: Array<string>): Array<string>
  /** Stem a newline-delimited buffer; output is newline-delimited. */
  stemBuffer(buffer: Buffer): Buffer
  /**
   * Tokenize text (unicode-word-aware) and stem every token in one FFI
   * crossing. This is the realistic hot-path.
   */
  tokenizeAndStem(text: string, options?: TokenizeOptions | undefined | null): Array<string>
  /** Tokenize-and-stem variant that returns a newline-delimited Buffer. */
  tokenizeAndStemToBuffer(text: string, options?: TokenizeOptions | undefined | null): Buffer
  get language(): string
}

/** Convenience for one-off usage. Documented as slow-path. */
export declare function stemOnce(language: string, word: string): string

export interface TokenizeOptions {
  /** Lowercase tokens before stemming. Default true. */
  lowercase?: boolean
  /** Minimum token length (shorter tokens are dropped). Default 2. */
  minTokenLength?: number
  /**
   * Drop tokens that appear in the embedded English stopword list.
   * Default false. (No other language lists are bundled in v0.1.)
   */
  stopwordsEn?: boolean
}
