/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Argon2Options {
  memoryCost?: number
  timeCost?: number
  parallelism?: number
  outputLen?: number
}

export declare function hash(password: string, options?: Argon2Options | undefined | null): Promise<string>

export declare function hashSync(password: string, options?: Argon2Options | undefined | null): string

export declare function verify(hash: string, password: string): Promise<boolean>

export declare function verifySync(hash: string, password: string): boolean
