/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Xxh32Hasher {
  constructor(seed?: number | undefined | null)
  update(chunk: Buffer): void
  digest(): number
  reset(seed?: number | undefined | null): void
}

export declare class Xxh3Hasher {
  constructor(seed?: bigint | undefined | null)
  update(chunk: Buffer): void
  digest(): bigint
  digestHex(): string
  reset(): void
}

export declare class Xxh64Hasher {
  constructor(seed?: bigint | undefined | null)
  update(chunk: Buffer): void
  digest(): bigint
  digestHex(): string
  reset(seed?: bigint | undefined | null): void
}

export declare function xxh3_128(input: Buffer, seed?: bigint | undefined | null): string

export declare function xxh3_64(input: Buffer, seed?: bigint | undefined | null): bigint

export declare function xxh3_64Many(input: Buffer, chunkSize: number, seed?: bigint | undefined | null): Buffer

export declare function xxh32(input: Buffer, seed?: number | undefined | null): number

export declare function xxh32Many(input: Buffer, chunkSize: number, seed?: number | undefined | null): Buffer

export declare function xxh64(input: Buffer, seed?: bigint | undefined | null): bigint

export declare function xxh64Many(input: Buffer, chunkSize: number, seed?: bigint | undefined | null): Buffer
