/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Xxh3Hasher {
  constructor(seed?: number | undefined | null)
  update(chunk: Buffer): void
  digest(): number
  digestHex(): string
  reset(): void
}

export declare function xxh3_128(input: Buffer, seed?: number | undefined | null): string

export declare function xxh3_64(input: Buffer, seed?: number | undefined | null): number

export declare function xxh32(input: Buffer, seed?: number | undefined | null): number

export declare function xxh64(input: Buffer, seed?: number | undefined | null): number
