/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface BcryptOptions {
  cost?: number
}

export declare function hash(password: string, options?: BcryptOptions | undefined | null): Promise<string>

export declare function hashSync(password: string, options?: BcryptOptions | undefined | null): string

export declare function verify(hash: string, password: string): Promise<boolean>

export declare function verifySync(hash: string, password: string): boolean
