/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DeepmergeOptions {
  /** 'concat' (default), 'overwrite' */
  arrayMerge?: string
}

export declare function mergeAllJson(values: Array<any>, options?: DeepmergeOptions | undefined | null): any

export declare function mergeJson(target: any, source: any, options?: DeepmergeOptions | undefined | null): any
