/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Tiktoken {
  static getEncoding(name: string): Tiktoken
  static encodingForModel(model: string): Tiktoken
  get name(): string
  /**
   * Encode with all special tokens allowed. Matches `tiktoken` npm's
   * `encode(text, "all")` and `gpt-tokenizer`'s default `encode`.
   */
  encode(text: string): Uint32Array
  /**
   * Encode without special-token expansion — treats `<|endoftext|>` etc.
   * as literal text.
   */
  encodeOrdinary(text: string): Uint32Array
  decode(tokens: Uint32Array): string
  /**
   * Fast path for budget-gating: returns the token count without
   * allocating the Uint32Array. Uses `encode_ordinary`.
   */
  countTokens(text: string): number
  /**
   * `tiktoken-rs` has no native early-exit encoder; this full-encodes
   * and compares. Kept for drop-in compatibility with gpt-tokenizer.
   */
  isWithinTokenLimit(text: string, limit: number): boolean
  /**
   * Batch-encode. Amortises the NAPI boundary over N texts — use when
   * chunking a document for RAG rather than calling `encode` in a loop.
   */
  encodeMany(texts: Array<string>): Array<Uint32Array>
  /**
   * Encode a chat conversation. Returns concatenated content tokens
   * plus the full ChatML-framed count (what OpenAI bills).
   */
  encodeChat(messages: Array<ChatMessage>, model: string): ChatEncodeResult
  /**
   * Token count for a full ChatML conversation, matching what OpenAI
   * bills. Equivalent to `gpt-tokenizer`'s `countChatCompletionTokens`.
   */
  countChatCompletionTokens(messages: Array<ChatMessage>, model: string): number
}

export interface ChatEncodeResult {
  /** Concatenated content tokens (no ChatML framing). */
  tokens: Uint32Array
  /**
   * Full ChatML token count including per-message framing and the
   * assistant-reply priming tokens — the number OpenAI bills for input.
   */
  count: number
}

export interface ChatMessage {
  role: string
  content: string
  name?: string
}
