/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Compressor {
  constructor(level?: number | undefined | null, dictionary?: Buffer | undefined | null)
  compress(input: Buffer): Buffer
  compressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare class Decompressor {
  constructor(dictionary?: Buffer | undefined | null)
  decompress(input: Buffer): Buffer
  decompressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare function compress(input: Buffer, level?: number | undefined | null): Buffer

export declare function decompress(input: Buffer): Buffer

export declare function trainDictionary(samples: Array<Buffer>, dictSize?: number | undefined | null): Buffer
