/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Compressor {
  constructor(level?: number | undefined | null, dictionary?: Buffer | undefined | null)
  compress(input: Buffer): Buffer
  compressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare class Decompressor {
  constructor(dictionary?: Buffer | undefined | null, maxOutputSize?: bigint | undefined | null)
  decompress(input: Buffer): Buffer
  decompressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare function compress(input: Buffer, level?: number | undefined | null): Buffer

export declare function decompress(input: Buffer): Buffer

export declare function trainDictionary(samples: Array<Buffer>, dictSize?: number | undefined | null): Buffer
