/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Compressor {
  constructor(level?: number | undefined | null, dictionary?: Buffer | undefined | null)
  compress(input: Buffer): Buffer
  compressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare class Decompressor {
  /**
   * Build a decompressor.
   *
   * `max_output_size` caps the size of any single decompressed payload
   * to defend against decompression bombs: untrusted zstd input can
   * expand by 1000×+ on a few KB of compressed bytes, exhausting
   * memory. The default is 256 MiB; pass `0` to disable the cap.
   */
  constructor(dictionary?: Buffer | undefined | null, maxOutputSize?: bigint | undefined | null)
  decompress(input: Buffer): Buffer
  decompressMany(inputs: Array<Buffer>): Array<Buffer>
}

export declare function compress(input: Buffer, level?: number | undefined | null): Buffer

export declare function decompress(input: Buffer): Buffer

export declare function trainDictionary(samples: Array<Buffer>, dictSize?: number | undefined | null): Buffer
