/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function countDiff(img1: Buffer, img2: Buffer, width: number, height: number, options?: PixelmatchOptions | undefined | null): number

export declare function pixelmatch(img1: Buffer, img2: Buffer, width: number, height: number, options?: PixelmatchOptions | undefined | null): PixelmatchResult

export interface PixelmatchOptions {
  threshold?: number
  includeAa?: boolean
  alpha?: number
  aaColor?: Array<number>
  diffColor?: Array<number>
  diffColorAlt?: Array<number>
  diffMask?: boolean
}

export interface PixelmatchResult {
  numDiff: number
  diff: Buffer
}
