/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function countDiff(img1: Buffer, img2: Buffer, width: number, height: number, options?: PixelmatchOptions | undefined | null): number

export declare function pixelmatch(img1: Buffer, img2: Buffer, width: number, height: number, options?: PixelmatchOptions | undefined | null): PixelmatchResult

export interface PixelmatchOptions {
  threshold?: number
  includeAa?: boolean
  alpha?: number
  aaColor?: Array<number>
  diffColor?: Array<number>
  diffColorAlt?: Array<number>
  diffMask?: boolean
}

export interface PixelmatchResult {
  numDiff: number
  diff: Buffer
}
