/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compile(source: string, options?: CompileOptions | undefined | null): CompileResult

export declare function compileMany(sources: Array<string>, options?: CompileOptions | undefined | null): Array<CompileResult>

export interface CompileOptions {
  /** Optional JSON-serializable object injected as `sys.inputs`. */
  data?: Record<string, string>
  /** Additional font TTF / OTF buffers to register. */
  fonts?: Array<Buffer>
}

export interface CompileResult {
  pdf: Buffer
  warnings: Array<Diagnostic>
}

export interface Diagnostic {
  severity: string
  message: string
}
