[package]
name = "amigo-sanitize-html"
version = "0.5.0"
edition.workspace = true

[lints]
workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
amigo-sanitize-html-core = { path = "../_sanitize-html-core" }

[build-dependencies]
napi-build = "2"
