/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function isClean(html?: string | number | undefined | null, options?: SanitizeOptions | undefined | null): boolean

export declare function sanitize(html?: string | number | undefined | null, options?: SanitizeOptions | undefined | null): string

export interface SanitizeOptions {
  allowedTags?: Array<string>
  allowedAttributes?: Record<string, Array<string>>
  allowedClasses?: Record<string, Array<string>>
  allowedSchemes?: Array<string>
  stripComments?: boolean
  linkRel?: string
  allowAllAttributes?: boolean
  maxDepth?: number
  maxInputBytes?: number
}

export declare function sanitizeStrict(html?: string | number | undefined | null, options?: SanitizeOptions | undefined | null): string
