/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Return the ISO-639-3 code of the most likely language, or `'und'` when the
 * input is shorter than `min_length` or no signal is detected.
 */
export declare function detect(text: string, options?: DetectOptions | undefined | null): string

/** Return a ranked list of top-N matches. */
export declare function detectAll(text: string, options?: DetectOptions | undefined | null): Array<LanguageMatch>

/**
 * Like `detect`, but returns `null` below `min_length` instead of `'und'`.
 * This is the recommended entry point for pipelines that prefer "I don't
 * know" over a guessed-but-wrong label.
 */
export declare function detectIfLong(text: string, options?: DetectOptions | undefined | null): string | null

/** Batch entry point — one FFI crossing amortises over N inputs. */
export declare function detectMany(texts: Array<string>, options?: DetectOptions | undefined | null): Array<string>

export interface DetectOptions {
  /**
   * Minimum input length in bytes before we even attempt detection.
   * Below this the trigram signal is unreliable — we return `'und'`.
   */
  minLength?: number
  /** ISO-639-3 allow-list. Empty = consider every language whatlang knows. */
  only?: Array<string>
  /** ISO-639-3 deny-list. Applied after `only`. */
  ignore?: Array<string>
}

/** True iff `whatlang` recognises the given ISO-639-3 code (lowercase). */
export declare function languageExists(code: string): boolean

export interface LanguageMatch {
  lang: string
  /** whatlang confidence in `[0, 1]`. Not directly comparable to franc's score. */
  confidence: number
}
