#!/usr/bin/env node

/**
 * Generates BENCHMARKS.md from bench-results.json and size-results.json.
 * Both files are produced by run-benchmarks.mjs and measure-size.mjs.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const benchPath = join(root, 'bench-results.json')
const sizePath = join(root, 'size-results.json')

function formatOps(hz) {
  if (hz >= 1_000_000) return `${(hz / 1_000_000).toFixed(2)}M`
  if (hz >= 1_000) return `${(hz / 1_000).toFixed(1)}K`
  if (hz >= 1) return `${hz.toFixed(1)}`
  return `${hz.toFixed(2)}`
}

function formatBytes(bytes) {
  if (bytes === null || bytes === undefined) return 'N/A'
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function speedup(amigoHz, otherHz) {
  if (!amigoHz || !otherHz) return '—'
  const ratio = amigoHz / otherHz
  if (ratio >= 1.05) return `**${ratio.toFixed(1)}x faster**`
  if (ratio <= 0.95) return `${(1 / ratio).toFixed(1)}x slower`
  return '~equal'
}

function detectCrate(name) {
  const lower = name.toLowerCase()
  if (lower.includes('slugify')) return 'slugify'
  if (lower.includes('argon2')) return 'argon2'
  if (lower.includes('xxh')) return 'xxhash'
  if (lower.includes('sanitize')) return 'sanitize-html'
  if (lower.includes('csv')) return 'csv'
  return 'other'
}

// --- Load data ---

let benchData = null
if (existsSync(benchPath)) {
  try {
    benchData = JSON.parse(readFileSync(benchPath, 'utf-8'))
  } catch (err) {
    console.warn(`Failed to parse ${benchPath}: ${err.message}`)
  }
}

let sizeData = null
if (existsSync(sizePath)) {
  try {
    sizeData = JSON.parse(readFileSync(sizePath, 'utf-8'))
  } catch (err) {
    console.warn(`Failed to parse ${sizePath}: ${err.message}`)
  }
}

if (!benchData && !sizeData) {
  console.error('No data found. Run `node scripts/run-benchmarks.mjs` and `node scripts/measure-size.mjs` first.')
  process.exit(1)
}

// --- Build markdown ---

const lines = []
lines.push('# Benchmarks')
lines.push('')
lines.push(`> Auto-generated by CI on ${new Date().toISOString().split('T')[0]}`)
lines.push(`> Node.js ${process.version}, ${process.platform} ${process.arch}`)
lines.push('')

// --- Performance section ---

if (benchData?.suites?.length) {
  const crateOrder = ['slugify', 'argon2', 'xxhash', 'sanitize-html', 'csv']
  const crateMap = new Map()

  for (const suite of benchData.suites) {
    const crate = detectCrate(suite.name)
    if (!crateMap.has(crate)) crateMap.set(crate, [])
    crateMap.get(crate).push(suite)
  }

  lines.push('## Performance')
  lines.push('')

  for (const crate of crateOrder) {
    const suiteList = crateMap.get(crate)
    if (!suiteList) continue

    lines.push(`### ${crate}`)
    lines.push('')

    for (const suite of suiteList) {
      const amigoEntry = suite.entries.find((e) => e.name.includes('@amigo'))
      const competitors = suite.entries.filter((e) => !e.name.includes('@amigo'))

      if (!amigoEntry || !competitors.length) continue

      lines.push(`**${suite.name}**`)
      lines.push('')
      lines.push('| Implementation | ops/sec | Comparison |')
      lines.push('|:---|---:|:---|')
      lines.push(`| ${amigoEntry.name} | ${formatOps(amigoEntry.hz)} | baseline |`)

      for (const comp of competitors) {
        lines.push(`| ${comp.name} | ${formatOps(comp.hz)} | ${speedup(amigoEntry.hz, comp.hz)} |`)
      }

      lines.push('')
    }
  }
}

// --- Size section ---

if (sizeData) {
  lines.push('## Package Size')
  lines.push('')
  lines.push('@amigo-labs = built binary + JS shim (single platform). Competitors = full `node_modules` after `npm install`.')
  lines.push('')
  lines.push('| Package | @amigo-labs (binary) | Competitor | Competitor (node_modules) | Difference |')
  lines.push('|:---|---:|:---|---:|:---|')

  for (const [crate, packages] of Object.entries(sizeData)) {
    const amigoKey = `@amigo-labs/${crate}`
    const amigoSize = packages[amigoKey]?.installSize

    for (const [pkg, data] of Object.entries(packages)) {
      if (pkg === amigoKey) continue
      const size = data.installSize
      let diff = ''
      if (size !== null && amigoSize) {
        if (size > amigoSize) {
          diff = `**amigo ${(size / amigoSize).toFixed(1)}x smaller**`
        } else {
          diff = `competitor ${(amigoSize / size).toFixed(1)}x smaller`
        }
      }
      lines.push(`| ${crate} | ${formatBytes(amigoSize)} | ${pkg} | ${formatBytes(size)} | ${diff} |`)
    }
  }

  lines.push('')
}

// --- Summary ---

if (benchData?.suites?.length) {
  lines.push('## Summary')
  lines.push('')

  const crateOrder = ['slugify', 'argon2', 'xxhash', 'sanitize-html', 'csv']
  for (const crate of crateOrder) {
    const suites = benchData.suites.filter((s) => detectCrate(s.name) === crate)
    if (!suites.length) continue

    const byCompetitor = new Map()
    for (const suite of suites) {
      const amigoEntry = suite.entries.find((e) => e.name.includes('@amigo'))
      if (!amigoEntry) continue
      for (const entry of suite.entries) {
        if (entry.name.includes('@amigo')) continue
        const key = entry.name
        if (!byCompetitor.has(key)) byCompetitor.set(key, [])
        byCompetitor.get(key).push(amigoEntry.hz / entry.hz)
      }
    }

    const parts = []
    for (const [comp, ratios] of byCompetitor) {
      const min = Math.min(...ratios)
      const max = Math.max(...ratios)
      if (min >= 1.05 && max >= 1.05) {
        const range = min.toFixed(1) === max.toFixed(1) ? `${min.toFixed(1)}x` : `${min.toFixed(1)}-${max.toFixed(1)}x`
        parts.push(`**${range} faster** than ${comp}`)
      } else if (max <= 0.95 && min <= 0.95) {
        const range = `${(1 / max).toFixed(1)}-${(1 / min).toFixed(1)}x`
        parts.push(`${range} slower than ${comp}`)
      } else {
        // Mixed: some faster, some slower
        const faster = ratios.filter((r) => r >= 1.05)
        const slower = ratios.filter((r) => r <= 0.95)
        if (faster.length && slower.length) {
          const fMax = Math.max(...faster)
          const sMax = Math.max(...slower.map((r) => 1 / r))
          parts.push(`up to **${fMax.toFixed(1)}x faster**, up to ${sMax.toFixed(1)}x slower vs ${comp}`)
        } else {
          parts.push(`~equal to ${comp}`)
        }
      }
    }

    if (parts.length) {
      lines.push(`- **${crate}**: ${parts.join('; ')}`)
    }
  }

  lines.push('')
}

const md = lines.join('\n')
const outPath = join(root, 'BENCHMARKS.md')
writeFileSync(outPath, md)
console.log(`Written to ${outPath}`)
