#!/usr/bin/env node

/**
 * Generates BENCHMARKS.md from bench-results.json and size-results.json.
 * Both files are produced by run-benchmarks.mjs and measure-size.mjs.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'

const root = process.cwd()
const benchPath = join(root, 'bench-results.json')
const sizePath = join(root, 'size-results.json')
const parityPath = join(root, 'parity-results.json')

const CRATE_ORDER = [
  'slugify',
  'argon2',
  'xxhash',
  'sanitize-html',
  'csv',
  'file-type',
  'inflate',
  'levenshtein',
  'nanoid',
  'encoding',
  'xml',
  'deep-equal',
  'deepmerge',
  'jwt',
  'zip',
]

function formatOps(hz) {
  if (hz >= 1_000_000) return `${(hz / 1_000_000).toFixed(2)}M`
  if (hz >= 1_000) return `${(hz / 1_000).toFixed(1)}K`
  if (hz >= 1) return `${hz.toFixed(1)}`
  return `${hz.toFixed(2)}`
}

function formatBytes(bytes) {
  if (bytes === null || bytes === undefined) return 'N/A'
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function compareToBaseline(amigoHz, baselineHz) {
  if (!amigoHz || !baselineHz) return '—'
  const ratio = amigoHz / baselineHz
  if (ratio >= 1.05) return `**${ratio.toFixed(1)}x faster**`
  if (ratio <= 0.95) return `${(1 / ratio).toFixed(1)}x slower`
  return '~equal'
}

function detectCrate(name) {
  const lower = name.toLowerCase()
  if (lower.includes('slugify')) return 'slugify'
  if (lower.includes('argon2')) return 'argon2'
  if (lower.includes('xxh')) return 'xxhash'
  if (lower.includes('sanitize')) return 'sanitize-html'
  if (lower.includes('csv')) return 'csv'
  if (lower.includes('file-type') || lower.includes('filetype')) return 'file-type'
  if (lower.includes('inflate') || lower.includes('deflate') || lower.includes('gzip')) return 'inflate'
  if (lower.includes('levenshtein')) return 'levenshtein'
  if (lower.includes('nanoid')) return 'nanoid'
  if (lower.includes('encoding')) return 'encoding'
  if (lower.includes('xml')) return 'xml'
  if (lower.includes('deep-equal') || lower.includes('deepequal')) return 'deep-equal'
  if (lower.includes('deepmerge')) return 'deepmerge'
  if (lower.includes('jwt')) return 'jwt'
  if (lower.includes('zip')) return 'zip'
  return 'other'
}

// --- Load data ---

let benchData = null
if (existsSync(benchPath)) {
  try {
    benchData = JSON.parse(readFileSync(benchPath, 'utf-8'))
  } catch (err) {
    console.warn(`Failed to parse ${benchPath}: ${err.message}`)
  }
}

let sizeData = null
if (existsSync(sizePath)) {
  try {
    sizeData = JSON.parse(readFileSync(sizePath, 'utf-8'))
  } catch (err) {
    console.warn(`Failed to parse ${sizePath}: ${err.message}`)
  }
}

let parityData = null
if (existsSync(parityPath)) {
  try {
    parityData = JSON.parse(readFileSync(parityPath, 'utf-8'))
  } catch (err) {
    console.warn(`Failed to parse ${parityPath}: ${err.message}`)
  }
}

if (!benchData && !sizeData) {
  console.error('No data found. Run `node scripts/run-benchmarks.mjs` and `node scripts/measure-size.mjs` first.')
  process.exit(1)
}

// --- Build markdown ---

const lines = []
lines.push('# Benchmarks')
lines.push('')
lines.push(`> Auto-generated by CI on ${new Date().toISOString().split('T')[0]}`)
lines.push(`> Node.js ${process.version}, ${process.platform} ${process.arch}`)
lines.push('')

// --- Performance section ---

if (benchData?.suites?.length) {
  const crateOrder = CRATE_ORDER
  const crateMap = new Map()

  for (const suite of benchData.suites) {
    const crate = detectCrate(suite.name)
    if (!crateMap.has(crate)) crateMap.set(crate, [])
    crateMap.get(crate).push(suite)
  }

  lines.push('## Performance')
  lines.push('')

  for (const crate of crateOrder) {
    const suiteList = crateMap.get(crate)
    if (!suiteList) continue

    // Collect all unique implementation names across all suites for this crate
    const allNames = new Set()
    for (const suite of suiteList) {
      for (const entry of suite.entries) allNames.add(entry.name)
    }

    // Separate amigo entries from competitors
    const amigoNames = [...allNames].filter((n) => n.includes('@amigo'))
    const competitorNames = [...allNames].filter((n) => !n.includes('@amigo'))
    const colOrder = [...competitorNames, ...amigoNames]

    lines.push(`### ${crate}`)
    lines.push('')
    lines.push(`| Scenario | ${colOrder.join(' | ')} |`)
    lines.push(`|:---|${colOrder.map(() => '---:|').join('')}`)

    for (const suite of suiteList) {
      const entryMap = new Map()
      for (const entry of suite.entries) entryMap.set(entry.name, entry)

      // Find the primary competitor baseline for speedup display
      const primaryComp = competitorNames.find((n) => entryMap.has(n))
      const baselineHz = primaryComp ? entryMap.get(primaryComp).hz : null

      const cells = colOrder.map((name) => {
        const entry = entryMap.get(name)
        if (!entry) return '—'
        const opsStr = formatOps(entry.hz)
        if (name.includes('@amigo') && baselineHz) {
          const cmp = compareToBaseline(entry.hz, baselineHz)
          return `**${opsStr}** (${cmp})`
        }
        return opsStr
      })

      lines.push(`| ${suite.name} | ${cells.join(' | ')} |`)
    }

    lines.push('')
  }
}

// --- Size section ---

if (sizeData) {
  lines.push('## Package Size')
  lines.push('')
  lines.push('@amigo-labs = built binary + JS shim (single platform). Competitors = full `node_modules` after `npm install`.')
  lines.push('')
  lines.push('| Package | @amigo-labs (binary) | Competitor | Competitor (node_modules) | Difference |')
  lines.push('|:---|---:|:---|---:|:---|')

  for (const [crate, packages] of Object.entries(sizeData)) {
    const amigoKey = `@amigo-labs/${crate}`
    const amigoSize = packages[amigoKey]?.installSize

    for (const [pkg, data] of Object.entries(packages)) {
      if (pkg === amigoKey) continue
      const size = data.installSize
      let diff = ''
      if (size !== null && amigoSize) {
        if (size > amigoSize) {
          diff = `**amigo ${(size / amigoSize).toFixed(1)}x smaller**`
        } else {
          diff = `competitor ${(amigoSize / size).toFixed(1)}x smaller`
        }
      }
      lines.push(`| ${crate} | ${formatBytes(amigoSize)} | ${pkg} | ${formatBytes(size)} | ${diff} |`)
    }
  }

  lines.push('')
}

// --- Parity section ---

if (parityData?.packages?.length) {
  lines.push('## Parity')
  lines.push('')
  lines.push(
    'Pass rate of each package against the upstream npm test suite (cloned into `__parity__/upstream.spec.ts`).',
  )
  lines.push('')
  lines.push('| Package | Passed | Total | Parity |')
  lines.push('|:---|---:|---:|---:|')

  const sortedPkgs = [...parityData.packages].sort((a, b) => {
    const ai = CRATE_ORDER.indexOf(a.name)
    const bi = CRATE_ORDER.indexOf(b.name)
    return (ai < 0 ? Infinity : ai) - (bi < 0 ? Infinity : bi)
  })

  for (const p of sortedPkgs) {
    const pct = p.total > 0 ? `${(p.parity * 100).toFixed(1)}%` : '—'
    lines.push(`| ${p.name} | ${p.passed} | ${p.total} | ${pct} |`)
  }

  if (parityData.aggregate?.total) {
    const aggPct = `${(parityData.aggregate.parity * 100).toFixed(1)}%`
    lines.push(
      `| **Aggregate** | **${parityData.aggregate.passed}** | **${parityData.aggregate.total}** | **${aggPct}** |`,
    )
  }

  lines.push('')
}

// --- Summary ---

if (benchData?.suites?.length) {
  lines.push('## Summary')
  lines.push('')

  const crateOrder = CRATE_ORDER
  for (const crate of crateOrder) {
    const suites = benchData.suites.filter((s) => detectCrate(s.name) === crate)
    if (!suites.length) continue

    const byCompetitor = new Map()
    for (const suite of suites) {
      const amigoEntry = suite.entries.find((e) => e.name.includes('@amigo'))
      if (!amigoEntry) continue
      for (const entry of suite.entries) {
        if (entry.name.includes('@amigo')) continue
        const key = entry.name
        if (!byCompetitor.has(key)) byCompetitor.set(key, [])
        byCompetitor.get(key).push(amigoEntry.hz / entry.hz)
      }
    }

    const parts = []
    for (const [comp, ratios] of byCompetitor) {
      const min = Math.min(...ratios)
      const max = Math.max(...ratios)
      if (min >= 1.05 && max >= 1.05) {
        const range = min.toFixed(1) === max.toFixed(1) ? `${min.toFixed(1)}x` : `${min.toFixed(1)}-${max.toFixed(1)}x`
        parts.push(`**${range} faster** than ${comp}`)
      } else if (max <= 0.95 && min <= 0.95) {
        const range = `${(1 / max).toFixed(1)}-${(1 / min).toFixed(1)}x`
        parts.push(`${range} slower than ${comp}`)
      } else {
        // Mixed: some faster, some slower
        const faster = ratios.filter((r) => r >= 1.05)
        const slower = ratios.filter((r) => r <= 0.95)
        if (faster.length && slower.length) {
          const fMax = Math.max(...faster)
          const sMax = Math.max(...slower.map((r) => 1 / r))
          parts.push(`up to **${fMax.toFixed(1)}x faster**, up to ${sMax.toFixed(1)}x slower vs ${comp}`)
        } else {
          parts.push(`~equal to ${comp}`)
        }
      }
    }

    if (parts.length) {
      lines.push(`- **${crate}**: ${parts.join('; ')}`)
    }
  }

  lines.push('')
}

const md = lines.join('\n')
const outPath = join(root, 'BENCHMARKS.md')
writeFileSync(outPath, md)
console.log(`Written to ${outPath}`)

// --- Write docs/data.json for GitHub Pages ---

const docsData = {
  generatedAt: new Date().toISOString().split('T')[0],
  nodeVersion: process.version,
  platform: `${process.platform} ${process.arch}`,
  benchmarks: benchData ?? null,
  sizes: sizeData ?? null,
  parity: parityData ?? null,
}

const docsDir = join(root, 'docs')
const docsPath = join(docsDir, 'data.json')
writeFileSync(docsPath, JSON.stringify(docsData, null, 2))
console.log(`Written to ${docsPath}`)

// --- Refresh docs/packages.json speedup strings ---

function formatRatio(x) {
  if (x < 2) return x.toFixed(2).replace(/\.?0+$/, '')
  if (x < 10) return x.toFixed(1).replace(/\.0$/, '')
  return Math.round(x).toString()
}

function entryVariant(name) {
  const i = name.indexOf(' ')
  return i === -1 ? '' : name.slice(i + 1)
}

function computeSpeedupString(suites) {
  const ratios = []
  for (const suite of suites) {
    const amigoEntries = suite.entries.filter((e) => e.name.includes('@amigo') && e.hz > 0)
    const competitors = suite.entries.filter((e) => !e.name.includes('@amigo') && e.hz > 0)
    if (!amigoEntries.length || !competitors.length) continue
    // Variant-match only when a suite has multiple amigo variants (e.g. encoding
    // small/100KB/10MB): otherwise the variant suffix encodes library qualifiers
    // (`slugify (npm)`, `file-type (upstream async)`) and strict matching would
    // discard the legitimate 1-vs-1 comparison.
    const variantMatch = new Set(amigoEntries.map((e) => entryVariant(e.name))).size > 1
    for (const amigo of amigoEntries) {
      const pool = variantMatch
        ? competitors.filter((e) => entryVariant(e.name) === entryVariant(amigo.name))
        : competitors
      if (!pool.length) continue
      // fastest competitor in pool → most conservative claim
      const bestHz = Math.max(...pool.map((e) => e.hz))
      ratios.push(amigo.hz / bestHz)
    }
  }
  if (!ratios.length) return 'TBD'
  const min = Math.min(...ratios)
  const max = Math.max(...ratios)
  if (min >= 1.05) {
    const lo = formatRatio(min)
    const hi = formatRatio(max)
    return lo === hi ? `${lo}× faster` : `${lo}–${hi}× faster`
  }
  if (max <= 0.95) {
    const lo = formatRatio(1 / max)
    const hi = formatRatio(1 / min)
    return lo === hi ? `${lo}× slower` : `${lo}–${hi}× slower`
  }
  // Mixed: show best win and worst regression
  const winners = ratios.filter((r) => r >= 1.05)
  const losers = ratios.filter((r) => r <= 0.95)
  const parts = []
  if (winners.length) parts.push(`up to ${formatRatio(Math.max(...winners))}× faster`)
  if (losers.length) parts.push(`${formatRatio(1 / Math.min(...losers))}× slower`)
  return parts.length ? parts.join(' / ') : '~equal'
}

const packagesPath = join(docsDir, 'packages.json')
if (benchData?.suites?.length && existsSync(packagesPath)) {
  const packagesData = JSON.parse(readFileSync(packagesPath, 'utf-8'))
  const suitesByCrate = new Map()
  for (const suite of benchData.suites) {
    const m = suite.file?.match(/^crates\/([^/]+)\//)
    if (!m) continue
    if (!suitesByCrate.has(m[1])) suitesByCrate.set(m[1], [])
    suitesByCrate.get(m[1]).push(suite)
  }
  for (const pkg of packagesData.packages ?? []) {
    const suites = suitesByCrate.get(pkg.name)
    if (suites?.length) pkg.speedup = computeSpeedupString(suites)
  }
  writeFileSync(packagesPath, JSON.stringify(packagesData, null, 2) + '\n')
  console.log(`Updated speedup strings in ${packagesPath}`)
}
