/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function split(text: string, options?: SplitOptions | undefined | null): Array<string>

export declare function splitBatch(texts: Array<string>, options?: SplitOptions | undefined | null): Array<Array<string>>

export declare function splitBatchToOffsets(texts: Array<string>, options?: SplitOptions | undefined | null): Array<Buffer>

export interface SplitOptions {
  /** Language code. Default: "en". Supported: en, de, fr, es, it, pt, nl. */
  language?: string
  /** Treat `

  ` as a hard sentence boundary. Default: false. */
  newlineBoundaries?: boolean
  /**
   * Keep leading/trailing whitespace on each emitted sentence.
   * Default: false — sentences are trimmed.
   */
  preserveWhitespace?: boolean
  /** Additional abbreviations to recognise (without trailing period). */
  customAbbreviations?: Array<string>
}

/**
 * Zero-copy hot-path. Returns a `Buffer` laid out as u32 little-endian
 * pairs: `[start0, end0, start1, end1, …]`.
 */
export declare function splitToOffsets(text: string, options?: SplitOptions | undefined | null): Buffer
