/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function decode(input: Buffer, encoding: string): string

export declare function encode(input: string, encoding: string): Buffer

export declare function encodingExists(encoding: string): boolean
