/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface EdgeRouting {
  source: string
  target: string
  points: Array<Point>
}

export interface EdgeSpec {
  source: string
  target: string
  /** Minimum rank distance between source and target. Default 1. */
  minlen?: number
  /** Edge weight (used by crossing-reduction heuristic). Default 1. */
  weight?: number
}

/** Compute a hierarchical layout. Single call per graph. */
export declare function layout(spec: LayoutSpec): LayoutResult

/** Batch: one FFI crossing for N independent layouts. */
export declare function layoutMany(specs: Array<LayoutSpec>): Array<LayoutResult>

export interface LayoutOptions {
  /** `"TB"` (top-bottom, default), `"BT"`, `"LR"`, or `"RL"`. */
  rankdir?: string
  /** Horizontal separation between nodes within the same rank. */
  nodesep?: number
  /** Vertical separation between ranks. Default 50. */
  ranksep?: number
  /** Outer left/right margin. Default 0. */
  marginx?: number
  /** Outer top/bottom margin. Default 0. */
  marginy?: number
}

export interface LayoutResult {
  nodes: Array<NodePosition>
  edges: Array<EdgeRouting>
  width: number
  height: number
}

export interface LayoutSpec {
  nodes: Array<NodeSpec>
  edges: Array<EdgeSpec>
  options?: LayoutOptions
}

export interface NodePosition {
  id: string
  x: number
  y: number
  width: number
  height: number
}

export interface NodeSpec {
  id: string
  width: number
  height: number
  /**
   * Optional: pin this node to a specific rank (0-indexed from the
   * top for `TB` / `BT`, from the left for `LR` / `RL`).
   */
  rank?: number
}

export interface Point {
  x: number
  y: number
}
