/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface EdgeRouting {
  source: string
  target: string
  points: Array<Point>
}

export interface EdgeSpec {
  source: string
  target: string
  minlen?: number
  weight?: number
}

export declare function layout(spec: LayoutSpec): LayoutResult

export declare function layoutMany(specs: Array<LayoutSpec>): Array<LayoutResult>

export interface LayoutOptions {
  rankdir?: string
  nodesep?: number
  ranksep?: number
  marginx?: number
  marginy?: number
}

export interface LayoutResult {
  nodes: Array<NodePosition>
  edges: Array<EdgeRouting>
  width: number
  height: number
}

export interface LayoutSpec {
  nodes: Array<NodeSpec>
  edges: Array<EdgeSpec>
  options?: LayoutOptions
}

export interface NodePosition {
  id: string
  x: number
  y: number
  width: number
  height: number
}

export interface NodeSpec {
  id: string
  width: number
  height: number
  rank?: number
}

export interface Point {
  x: number
  y: number
}
