/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Pure character-length counter. */
export declare function countChars(text: string): number

/** Tiktoken token count with a named encoding. */
export declare function countTokens(text: string, encoding?: string | undefined | null): number

/** Markdown-aware splitter: respects heading/paragraph/list boundaries. */
export declare function splitMarkdown(text: string, options?: SplitterOptions | undefined | null): Array<string>

export declare function splitMarkdownBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>

export interface SplitterOptions {
  /** Maximum chunk size (in chars or tokens, depending on `lengthMetric`). */
  chunkSize?: number
  /** Chunk overlap (same unit as `chunkSize`). Default: 0. */
  chunkOverlap?: number
  /** `"chars"` (default), `"tiktoken:cl100k_base"`, or `"tiktoken:o200k_base"`. */
  lengthMetric?: string
}

/** RecursiveCharacterTextSplitter — the 80% API. */
export declare function splitText(text: string, options?: SplitterOptions | undefined | null): Array<string>

/** Batch — one FFI crossing for N docs. */
export declare function splitTextBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>
