/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function countChars(text: string): number

export declare function countTokens(text: string, encoding?: string | undefined | null): number

export declare function splitMarkdown(text: string, options?: SplitterOptions | undefined | null): Array<string>

export declare function splitMarkdownBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>

export interface SplitterOptions {
  chunkSize?: number
  chunkOverlap?: number
  lengthMetric?: string
}

export declare function splitText(text: string, options?: SplitterOptions | undefined | null): Array<string>

export declare function splitTextBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>
