/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function countChars(text: string): number

export declare function countTokens(text: string, encoding?: string | undefined | null): number

export declare function splitMarkdown(text: string, options?: SplitterOptions | undefined | null): Array<string>

export declare function splitMarkdownBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>

export interface SplitterOptions {
  chunkSize?: number
  chunkOverlap?: number
  lengthMetric?: string
}

export declare function splitText(text: string, options?: SplitterOptions | undefined | null): Array<string>

export declare function splitTextBatch(texts: Array<string>, options?: SplitterOptions | undefined | null): Array<Array<string>>
