/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Cleaner modern alias for `get`. */
export declare function distance(a: string, b: string, options?: LevenshteinOptions | undefined | null): number

/** fast-levenshtein-compatible API. */
export declare function get(a: string, b: string, options?: LevenshteinOptions | undefined | null): number

export interface LevenshteinOptions {
  /**
   * fast-levenshtein-compatible collator flag: when true, both strings are
   * lowercased before comparison (UTF-8 aware).
   */
  useCollator?: boolean
}
