/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Cleaner modern alias for `get`. */
export declare function distance(a: string, b: string, options?: LevenshteinOptions | undefined | null): number

/**
 * Batch API: compute distance for N pairs in a single FFI call. For small
 * strings the N-API crossing dominates compute time, so amortizing over
 * many pairs is the difference between losing and beating fast-levenshtein.
 * `a_list` and `b_list` must have the same length.
 */
export declare function distanceBatch(aList: Array<string>, bList: Array<string>, options?: LevenshteinOptions | undefined | null): Array<number>

/** fast-levenshtein-compatible API. */
export declare function get(a: string, b: string, options?: LevenshteinOptions | undefined | null): number

export interface LevenshteinOptions {
  /**
   * fast-levenshtein-compatible collator flag: when true, both strings are
   * lowercased before comparison (UTF-8 aware).
   */
  useCollator?: boolean
}
