#!/usr/bin/env node
/**
 * audit-crates — verify every crate in crates/* conforms to the reference
 * conventions (argon2/csv/sanitize-html/slugify/xxhash). Outputs a markdown
 * report with a per-crate status table and a prioritized gap-fix checklist.
 *
 * Run from the monorepo root:
 *   node .claude/skills/audit-crates/scripts/audit.mjs
 *   node .claude/skills/audit-crates/scripts/audit.mjs --json
 */

import { readdirSync, existsSync, readFileSync, statSync } from 'node:fs'
import { join } from 'node:path'

const ROOT = process.cwd()
const CRATES_DIR = join(ROOT, 'crates')
const PLATFORMS = [
  'darwin-arm64',
  'darwin-x64',
  'linux-arm64-gnu',
  'linux-x64-gnu',
  'linux-x64-musl',
  'win32-x64-msvc',
]
const REGISTRY_FIELDS = ['title', 'description', 'speedup', 'npmUrl', 'sourceUrl', 'readmeUrl']

const asJson = process.argv.includes('--json')

function die(msg) {
  console.error(`[audit-crates] ${msg}`)
  process.exit(2)
}

if (!existsSync(CRATES_DIR)) {
  die(`crates/ directory not found in ${ROOT}. Run from the monorepo root.`)
}

function readJson(path) {
  try {
    return JSON.parse(readFileSync(path, 'utf-8'))
  } catch {
    return null
  }
}

function isDir(p) {
  try { return statSync(p).isDirectory() } catch { return false }
}

function listCrates() {
  return readdirSync(CRATES_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory() && e.name !== '_template')
    .map((e) => e.name)
    .sort()
}

function auditCrate(name) {
  const dir = join(CRATES_DIR, name)
  const pkg = readJson(join(dir, 'package.json')) ?? {}
  const scripts = pkg.scripts ?? {}
  const devDeps = pkg.devDependencies ?? {}

  const npmDir = join(dir, 'npm')
  const missingPlatforms = PLATFORMS.filter((p) => !isDir(join(npmDir, p)))

  return {
    name,
    // modern convention
    conformanceDir: isDir(join(dir, '__conformance__')),
    parityFile: existsSync(join(dir, '__conformance__', 'parity.spec.ts')),
    fuzzFile: existsSync(join(dir, '__conformance__', 'fuzz.spec.ts')),
    testConformanceScript: typeof scripts['test:conformance'] === 'string',
    testAllScript: typeof scripts['test:all'] === 'string',
    // legacy markers
    legacyParityDir: isDir(join(dir, '__parity__')),
    legacyTestParityScript: typeof scripts['test:parity'] === 'string',
    // shared
    testScript: typeof scripts.test === 'string',
    benchScript: typeof scripts.bench === 'string',
    benchFile: existsSync(join(dir, '__bench__', 'index.bench.ts')),
    testDir: isDir(join(dir, '__test__')),
    fastCheck: typeof devDeps['fast-check'] === 'string',
    readme: existsSync(join(dir, 'README.md')),
    npmDir: isDir(npmDir),
    missingPlatforms,
    cargo: existsSync(join(dir, 'Cargo.toml')),
    lib: existsSync(join(dir, 'src', 'lib.rs')),
  }
}

function auditDocs(crates) {
  // docs/packages.json is hand-edited (brand + marquee + heroTaglines + packages).
  // docs/data.json is auto-generated by scripts/generate-report.mjs (benchmarks + sizes + parity).
  const pkgs = readJson(join(ROOT, 'docs', 'packages.json'))
  const data = readJson(join(ROOT, 'docs', 'data.json'))

  const listed = new Set((pkgs?.packages ?? []).map((p) => p.name))
  const missingInPackagesJson = crates.filter((c) => !listed.has(c))

  const fieldGaps = []
  for (const p of pkgs?.packages ?? []) {
    const gaps = REGISTRY_FIELDS.filter((f) => !p[f] || String(p[f]).trim() === '')
    if (gaps.length) fieldGaps.push({ name: p.name, gaps })
  }

  const marqueeEntry = (pkgs?.marquee ?? []).find((m) => m.k === 'PACKAGES')
  const marqueeCount = marqueeEntry ? Number(marqueeEntry.v) : null
  const marqueeExpected = crates.length
  const marqueeOk = marqueeCount === marqueeExpected

  return {
    pkgsJsonFound: pkgs !== null,
    dataJsonFound: data !== null,
    missingInPackagesJson,
    fieldGaps,
    marqueeCount,
    marqueeExpected,
    marqueeOk,
  }
}

const crateNames = listCrates()
const crates = crateNames.map(auditCrate)
const docs = auditDocs(crateNames)

// --- Priority buckets for the checklist ---

const legacyCrates = crates.filter((r) => r.legacyParityDir || r.legacyTestParityScript)
const missingConformance = crates.filter((r) => !r.parityFile || !r.fuzzFile)
const missingScriptsOrDeps = crates.filter((r) => !r.testConformanceScript || !r.testAllScript || !r.fastCheck)
const missingReadme = crates.filter((r) => !r.readme)
const missingNpm = crates.filter((r) => !r.npmDir || r.missingPlatforms.length > 0)
const missingBench = crates.filter((r) => !r.benchFile)

const clean =
  legacyCrates.length === 0 &&
  missingConformance.length === 0 &&
  missingScriptsOrDeps.length === 0 &&
  missingReadme.length === 0 &&
  missingNpm.length === 0 &&
  missingBench.length === 0 &&
  docs.missingInPackagesJson.length === 0 &&
  docs.marqueeOk &&
  docs.fieldGaps.length === 0

// --- JSON mode: dump everything and exit ---

if (asJson) {
  const out = {
    root: ROOT,
    crates,
    docs,
    summary: {
      clean,
      legacy: legacyCrates.map((r) => r.name),
      missingConformance: missingConformance.map((r) => r.name),
      missingScriptsOrDeps: missingScriptsOrDeps.map((r) => r.name),
      missingReadme: missingReadme.map((r) => r.name),
      missingNpm: missingNpm.map((r) => r.name),
      missingBench: missingBench.map((r) => r.name),
    },
  }
  console.log(JSON.stringify(out, null, 2))
  process.exit(clean ? 0 : 1)
}

// --- Markdown report ---

const mark = (b) => (b ? '✓' : '✗')
const lines = []

lines.push('# Crate Consistency Audit')
lines.push('')
lines.push(`Root: \`${ROOT}\``)
lines.push(`Crates scanned: **${crateNames.length}**`)
lines.push('')

lines.push('## Per-Crate Status')
lines.push('')
lines.push('| Crate | `__conf__` | parity | fuzz | `test:conf` | `test:all` | fast-check | README | `npm/` | bench | legacy |')
lines.push('|---|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|:-:|')
for (const r of crates) {
  const legacy = r.legacyParityDir || r.legacyTestParityScript ? '⚠' : ''
  const npmCell = r.npmDir
    ? r.missingPlatforms.length === 0
      ? '✓'
      : `✗ (−${r.missingPlatforms.length})`
    : '✗'
  lines.push(
    `| ${r.name} | ${mark(r.conformanceDir)} | ${mark(r.parityFile)} | ${mark(r.fuzzFile)} | ${mark(r.testConformanceScript)} | ${mark(r.testAllScript)} | ${mark(r.fastCheck)} | ${mark(r.readme)} | ${npmCell} | ${mark(r.benchFile)} | ${legacy} |`,
  )
}
lines.push('')

lines.push('## Docs Registry')
lines.push('')
if (!docs.pkgsJsonFound) lines.push('- ✗ `docs/packages.json` not found or invalid JSON')
if (!docs.dataJsonFound) lines.push('- ✗ `docs/data.json` not found or invalid JSON')
if (docs.missingInPackagesJson.length) {
  lines.push(
    `- ✗ Not listed in \`docs/packages.json\`: ${docs.missingInPackagesJson.map((c) => `\`${c}\``).join(', ')}`,
  )
}
for (const { name, gaps } of docs.fieldGaps) {
  lines.push(`- ⚠ \`${name}\` in \`docs/packages.json\` missing fields: ${gaps.join(', ')}`)
}
if (docs.marqueeOk) {
  lines.push(`- ✓ \`docs/packages.json\` marquee PACKAGES = ${docs.marqueeCount}`)
} else {
  lines.push(`- ✗ \`docs/packages.json\` marquee PACKAGES = ${docs.marqueeCount ?? 'missing'}, expected ${docs.marqueeExpected}`)
}
lines.push('')

lines.push('## Gap-Fix Checklist')
lines.push('')
lines.push('_Priority: 🔴 legacy first (consolidates conventions) → 🟠 test infrastructure → 🟡 polish_')
lines.push('')

if (legacyCrates.length) {
  lines.push('### 🔴 Legacy convention (modernize)')
  for (const r of legacyCrates) {
    const bits = []
    if (r.legacyParityDir) bits.push('rename `__parity__/` → `__conformance__/`')
    if (r.legacyTestParityScript) bits.push('rename script `test:parity` → `test:conformance`')
    lines.push(`- [ ] **${r.name}** — ${bits.join('; ')}`)
  }
  lines.push('')
}

if (missingConformance.length) {
  lines.push('### 🟠 Missing conformance spec files')
  for (const r of missingConformance) {
    const bits = []
    if (!r.parityFile) bits.push('`parity.spec.ts`')
    if (!r.fuzzFile) bits.push('`fuzz.spec.ts`')
    lines.push(`- [ ] **${r.name}** — add ${bits.join(' + ')} under \`__conformance__/\``)
  }
  lines.push('')
}

if (missingScriptsOrDeps.length) {
  lines.push('### 🟠 Missing package.json entries')
  for (const r of missingScriptsOrDeps) {
    const bits = []
    if (!r.testConformanceScript) bits.push('`test:conformance` script')
    if (!r.testAllScript) bits.push('`test:all` script')
    if (!r.fastCheck) bits.push('`fast-check` devDependency')
    lines.push(`- [ ] **${r.name}** — add ${bits.join(', ')}`)
  }
  lines.push('')
}

if (missingBench.length) {
  lines.push('### 🟡 Missing benchmark suite')
  for (const r of missingBench) {
    lines.push(`- [ ] **${r.name}** — add \`__bench__/index.bench.ts\``)
  }
  lines.push('')
}

if (missingReadme.length) {
  lines.push('### 🟡 Missing README')
  for (const r of missingReadme) {
    lines.push(`- [ ] **${r.name}** — add \`README.md\``)
  }
  lines.push('')
}

if (missingNpm.length) {
  lines.push('### 🟡 Missing `npm/` platform stub directories')
  for (const r of missingNpm) {
    if (!r.npmDir) {
      lines.push(`- [ ] **${r.name}** — create \`npm/\` with all 6 platform subdirs`)
    } else {
      lines.push(
        `- [ ] **${r.name}** — missing ${r.missingPlatforms.map((p) => `\`${p}\``).join(', ')}`,
      )
    }
  }
  lines.push('')
}

if (
  docs.missingInPackagesJson.length ||
  !docs.marqueeOk ||
  docs.fieldGaps.length ||
  !docs.pkgsJsonFound ||
  !docs.dataJsonFound
) {
  lines.push('### 🟡 Docs registry')
  for (const name of docs.missingInPackagesJson) {
    lines.push(
      `- [ ] Add \`${name}\` entry to \`docs/packages.json\` (name, title, description, speedup, npmUrl, sourceUrl, readmeUrl)`,
    )
  }
  for (const { name, gaps } of docs.fieldGaps) {
    lines.push(`- [ ] Fill in \`${name}\` fields: ${gaps.join(', ')}`)
  }
  if (!docs.marqueeOk) {
    lines.push(
      `- [ ] Update \`docs/packages.json\` marquee \`PACKAGES\`: ${docs.marqueeCount ?? 'missing'} → ${docs.marqueeExpected}`,
    )
  }
  lines.push('')
}

if (clean) {
  lines.push('**All crates conform to the reference conventions. ✓**')
} else {
  const gapCount =
    legacyCrates.length +
    missingConformance.length +
    missingScriptsOrDeps.length +
    missingReadme.length +
    missingNpm.length +
    missingBench.length +
    docs.missingInPackagesJson.length +
    docs.fieldGaps.length +
    (docs.marqueeOk ? 0 : 1)
  lines.push(`_Summary: **${gapCount} gap(s)** across ${crateNames.length} crates._`)
}

console.log(lines.join('\n'))
process.exit(clean ? 0 : 1)
