/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function parse(buf: Buffer, options?: PdfParseOptions | undefined | null): Promise<unknown>

export declare function parseSync(buf: Buffer, options?: PdfParseOptions | undefined | null): PdfParseResult

export interface PdfParseOptions {
  max?: number
  password?: string
}

export interface PdfParseResult {
  text: string
  numpages: number
  info: Record<string, string>
  metadata?: string
  version: string
}
