/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parse(buf: Buffer, options?: PdfParseOptions | undefined | null): Promise<unknown>

export declare function parseSync(buf: Buffer, options?: PdfParseOptions | undefined | null): PdfParseResult

export interface PdfParseOptions {
  max?: number
  password?: string
}

export interface PdfParseResult {
  text: string
  numpages: number
  info: Record<string, string>
  metadata?: string
  version: string
}
