/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Promise-shaped drop-in for upstream `pdf-parse`. Thin wrapper
 * around `parseSync`; runs the work on libuv's thread pool.
 */
export declare function parse(buf: Buffer, options?: PdfParseOptions | undefined | null): Promise<unknown>

/**
 * Extract text + metadata. Synchronous — pdf-extract runs on the
 * calling thread. For server workloads, run on a worker pool.
 */
export declare function parseSync(buf: Buffer, options?: PdfParseOptions | undefined | null): PdfParseResult

export interface PdfParseOptions {
  /** Process at most N pages (default: all). Upstream's `max` option. */
  max?: number
  /** Password for encrypted PDFs. RC4 + AES-128 standard security. */
  password?: string
}

export interface PdfParseResult {
  text: string
  numpages: number
  info: Record<string, string>
  metadata?: string
  version: string
}
