/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface LinkifyOptions {
  fuzzyLink?: boolean
  fuzzyEmail?: boolean
}

export interface LinkMatch {
  schema: string
  index: number
  lastIndex: number
  text: string
  url: string
}

export declare function matches(text: string, options?: LinkifyOptions | undefined | null): Array<LinkMatch>

export declare function matchOffsets(text: Buffer, options?: LinkifyOptions | undefined | null): Buffer

export declare function test(text: string, options?: LinkifyOptions | undefined | null): boolean
