/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface LinkifyOptions {
  fuzzyLink?: boolean
  fuzzyEmail?: boolean
}

export interface LinkMatch {
  schema: string
  index: number
  lastIndex: number
  text: string
  url: string
}

export declare function matches(text: string, options?: LinkifyOptions | undefined | null): Array<LinkMatch>

export declare function matchOffsets(text: Buffer, options?: LinkifyOptions | undefined | null): Buffer

export declare function test(text: string, options?: LinkifyOptions | undefined | null): boolean
