/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuse {
  constructor(recordsJson: Array<string>, options?: FuseOptions | undefined | null)
  search(query: string, limit?: number | undefined | null): Array<FuseResult>
  size(): number
}

export interface FuseKey {
  name: string
  weight?: number
}

export interface FuseOptions {
  keys?: Array<FuseKey>
  threshold?: number
  /**
   * Default `limit` applied when `Fuse.search` is called without one.
   * Per-call `limit` always wins. `None` means "no cap".
   */
  defaultLimit?: number
}

export interface FuseResult {
  refIndex: number
  score: number
}
