/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare class Fuse {
  constructor(recordsJson: Array<string>, options?: FuseOptions | undefined | null)
  search(query: string, limit?: number | undefined | null): Array<FuseResult>
  size(): number
}

export interface FuseKey {
  name: string
  weight?: number
}

export interface FuseOptions {
  keys?: Array<FuseKey>
  threshold?: number
  /**
   * Default `limit` applied when `Fuse.search` is called without one.
   * Per-call `limit` always wins. `None` means "no cap".
   */
  defaultLimit?: number
}

export interface FuseResult {
  refIndex: number
  score: number
}
