/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Fuse {
  constructor(recordsJson: Array<string>, options?: FuseOptions | undefined | null)
  search(query: string, limit?: number | undefined | null): Array<FuseResult>
  size(): number
}

export interface FuseKey {
  name: string
  weight?: number
}

export interface FuseOptions {
  keys?: Array<FuseKey>
  includeScore?: boolean
  threshold?: number
  limit?: number
}

export interface FuseResult {
  refIndex: number
  score: number
}
