/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export interface DecodedPng {
  width: number
  height: number
  data: Buffer
  depth: number
  colorType: string
}

export declare function decodeRgba(input: Buffer): DecodedPng

/** Encoder options. v0.1 has no tunables — preserved for the v0.2 wire-up. */
export interface EncodeOptions {
  deflateLevel?: number
}

export declare function encodeRgba(pixels: Buffer, width: number, height: number, opts?: EncodeOptions | undefined | null): Buffer

export declare function read(input: Buffer): DecodedPng

export declare function write(png: DecodedPng, opts?: EncodeOptions | undefined | null): Buffer
