/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DecodedPng {
  width: number
  height: number
  data: Buffer
  depth: number
  colorType: string
}

export declare function decodeRgba(input: Buffer): DecodedPng

/**
 * Encoder options. v0.1 has no tunables — the encoder always uses
 * image-rs `png`'s default DEFLATE settings, regardless of any value
 * passed in `deflate_level`. The field is preserved for the v0.2
 * wire-up so callers don't need an API churn when it lands.
 */
export interface EncodeOptions {
  deflateLevel?: number
}

export declare function encodeRgba(pixels: Buffer, width: number, height: number, opts?: EncodeOptions | undefined | null): Buffer

export declare function read(input: Buffer): DecodedPng

export declare function write(png: DecodedPng, opts?: EncodeOptions | undefined | null): Buffer
