/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface DecodedPng {
  width: number
  height: number
  data: Buffer
  depth: number
  colorType: string
}

export declare function decodeRgba(input: Buffer): DecodedPng

export interface EncodeOptions {
  deflateLevel?: number
}

export declare function encodeRgba(pixels: Buffer, width: number, height: number, opts?: EncodeOptions | undefined | null): Buffer

export declare function read(input: Buffer): DecodedPng

export declare function write(png: DecodedPng, opts?: EncodeOptions | undefined | null): Buffer
